'use strict';
// AGENTS.md emitter — portable, standards-compliant agent rules (the Linux-Foundation AGENTS.md
// convention read natively by Codex, Cursor, Copilot, Gemini CLI, Aider, Windsurf, Zed). Generated
// from data agentic-os already computes (stack detect + package scripts + the map), so the plugin's
// mapped knowledge is portable across EVERY agent, not just Claude Code. Encodes only what agents
// can't trivially discover themselves (build/test commands, architecture, conventions, gotchas).
const fs = require('node:fs');
const path = require('node:path');

const SENTINEL_START = '<!-- agentic-os:agents-md:start -->';
const SENTINEL_END = '<!-- agentic-os:agents-md:end -->';

function readJson(p) { try { return JSON.parse(fs.readFileSync(p, 'utf8')); } catch { return null; } }

function detectCommands(root) {
  const pj = readJson(path.join(root, 'package.json')) || {};
  const s = pj.scripts || {};
  const pick = (...keys) => { for (const k of keys) if (s[k]) return `npm run ${k}`; return null; };
  return {
    install: fs.existsSync(path.join(root, 'package-lock.json')) ? 'npm ci' : (fs.existsSync(path.join(root, 'pnpm-lock.yaml')) ? 'pnpm install' : (fs.existsSync(path.join(root, 'yarn.lock')) ? 'yarn' : 'npm install')),
    build: pick('build'),
    test: s.test ? 'npm test' : pick('test:unit', 'jest', 'vitest'),
    lint: pick('lint', 'eslint'),
    typecheck: pick('typecheck', 'tsc', 'type-check'),
    dev: pick('dev', 'start'),
  };
}

function renderBody(root, { stack, map } = {}) {
  const cmd = detectCommands(root);
  const eco = readJson(path.join(root, '.ecosystem', 'map.json')) || map || {};
  const areas = readJson(path.join(root, '.ecosystem', 'path-to-area.json'));
  const areaNames = areas ? [...new Set((areas.mappings || []).map((m) => m.area))].filter((a) => a && a !== 'ungrouped' && a !== 'root') : [];
  const st = stack || eco.stack || {};
  const lines = [];
  lines.push('# AGENTS.md', '', '> Generated by agentic-os from the codebase map. Portable agent guidance (AGENTS.md standard).', '');
  lines.push('## Commands', '');
  for (const [label, c] of [['Install', cmd.install], ['Build', cmd.build], ['Test', cmd.test], ['Lint', cmd.lint], ['Typecheck', cmd.typecheck], ['Dev', cmd.dev]]) {
    if (c) lines.push(`- **${label}:** \`${c}\``);
  }
  lines.push('');
  if (st && (st.languages || st.frameworks || st.runtime)) {
    lines.push('## Stack', '');
    if (st.languages) lines.push(`- Languages: ${[].concat(st.languages).join(', ')}`);
    if (st.frameworks) lines.push(`- Frameworks: ${[].concat(st.frameworks).join(', ')}`);
    if (st.runtime) lines.push(`- Runtime: ${st.runtime}`);
    lines.push('');
  }
  if (areaNames.length) {
    lines.push('## Architecture areas', '', '_The codebase groups into these areas. See `.ecosystem/areas/<area>.md` for each map._', '');
    for (const a of areaNames.slice(0, 30)) lines.push(`- \`${a}\``);
    lines.push('');
  }
  if (Array.isArray(eco.routes) && eco.routes.length) lines.push(`- This service exposes **${eco.routes.length} routes**; check guards before changing any auth-adjacent handler.`, '');
  lines.push('## Conventions agents must follow', '',
    '- Match the surrounding code style; do not introduce new dependencies without need.',
    '- Every data query in a multi-tenant area must be scoped to the tenant key.',
    '- Read the relevant `.ecosystem/areas/<area>.md` before editing that area; verify the doc against code.',
    '- Run the test + lint commands above before declaring work done.',
    '- agentic-os maintains a deeper map in `.ecosystem/` and richer guidance in `CLAUDE.md` (Claude Code).', '');
  return lines.join('\n');
}

// Write AGENTS.md, preserving any human content OUTSIDE the sentinel block (create-or-merge).
function writeAgentsMd(root, ctx = {}) {
  const file = path.join(root, 'AGENTS.md');
  const block = SENTINEL_START + '\n' + renderBody(root, ctx) + '\n' + SENTINEL_END;
  let existing = ''; try { existing = fs.readFileSync(file, 'utf8'); } catch {}
  let next;
  if (existing.includes(SENTINEL_START) && existing.includes(SENTINEL_END)) {
    next = existing.replace(new RegExp(SENTINEL_START + '[\\s\\S]*?' + SENTINEL_END), block);
  } else if (existing.trim()) {
    next = block + '\n\n' + existing;
  } else { next = block + '\n'; }
  fs.writeFileSync(file, next);
  return file;
}

module.exports = { renderBody, writeAgentsMd, detectCommands, SENTINEL_START, SENTINEL_END };
