// src/git-hooks.js
// The managed git pre-push hook: the PRIMARY local defense (Grok vision) — runs the gate pack
// before any push, blocks on failure, bypassable with AGENTIC_OS_OVERRIDE=1 (consistent with the
// safety bumper). GitHub/GitLab CI is the backup net. Pure string builders so they're testable.

function prePushScript({ advisory = false } = {}) {
  // advisory = inform but never block (the right default for a repo with pre-existing tech debt — you
  // can't assume it passes its own gates on day one). enforce mode (advisory=false) blocks on failure.
  const onFail = advisory
    ? `  echo ""
  echo "[agentic-os] ⚠ pre-push checks reported issues (ADVISORY — not blocking)."
  echo "  Flip to enforcing once clean:  node <plugin>/bin/install-git-hooks.js . --enforce"
  exit 0`
    : `  echo ""
  echo "[agentic-os] ❌ pre-push checks failed."
  echo "  Fix the failures above, or bypass once with:  AGENTIC_OS_OVERRIDE=1 git push"
  exit 1`;
  return `#!/usr/bin/env bash
# agentic-os pre-push gate (managed — do not edit; regenerated by install-git-hooks).
# Mode: ${advisory ? 'ADVISORY (informs, never blocks)' : 'ENFORCING (blocks on failure)'}.
# Bypass once:  AGENTIC_OS_OVERRIDE=1 git push
if [ "\${AGENTIC_OS_OVERRIDE:-}" = "1" ]; then
  echo "[agentic-os] pre-push BYPASSED (AGENTIC_OS_OVERRIDE=1)"; exit 0
fi
ROOT="$(git rev-parse --show-toplevel)"
CHECK="$ROOT/.ecosystem/ci-check.sh"
if [ ! -f "$CHECK" ]; then
  echo "[agentic-os] no .ecosystem/ci-check.sh found — skipping (run /agentic-os:bootstrap-ecosystem to generate it)"
  exit 0
fi
echo "[agentic-os] running pre-push checks…"
if bash "$CHECK"; then
  exit 0
else
${onFail}
fi
`;
}

// commit-msg hook: validate Conventional Commits format (builtin — no commitlint dependency).
// Bypass: AGENTIC_OS_OVERRIDE=1. Merge/revert/fixup commits are exempt.
function commitMsgScript() {
  return `#!/usr/bin/env bash
# agentic-os commit-msg gate (managed) — enforces Conventional Commits. Bypass: AGENTIC_OS_OVERRIDE=1
[ "\${AGENTIC_OS_OVERRIDE:-}" = "1" ] && exit 0
MSG_FILE="$1"
FIRST="$(head -n1 "$MSG_FILE")"
# exempt merges/reverts/fixups/auto
case "$FIRST" in
  "Merge "*|"Revert "*|"fixup!"*|"squash!"*|"Bumping"*) exit 0 ;;
esac
if echo "$FIRST" | grep -qiE '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\\([a-z0-9_.-]+\\))?!?: .+'; then
  exit 0
fi
echo "[agentic-os] ✋ commit message is not Conventional Commits format."
echo "  Use:  type(scope): summary   e.g.  feat(auth): add magic-link login"
echo "  types: feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert"
echo "  Got:  $FIRST"
echo "  Bypass once:  AGENTIC_OS_OVERRIDE=1 git commit ..."
exit 1
`;
}

// A README for the managed hooks dir so a human who finds it understands core.hooksPath.
function hooksReadme() {
  return `# agentic-os managed git hooks

This directory is the repo's \`core.hooksPath\` (set by \`agentic-os install-git-hooks\`).
\`pre-push\` runs \`.ecosystem/ci-check.sh\` before every push (lint/typecheck/test/dep-audit/
secret-scan). It BLOCKS the push on failure; bypass once with \`AGENTIC_OS_OVERRIDE=1 git push\`.

To stop using managed hooks: \`git config --unset core.hooksPath\`.
`;
}

module.exports = { prePushScript, commitMsgScript, hooksReadme };
