import type { CostCity } from './types';

// AUTO-GENERATED by the content workflow (do not hand-edit — regenerate instead).
export const GENERATED_COST_CITIES: CostCity[] = [
  {
    "slug": "houston",
    "city": "Houston",
    "stateAbbr": "TX",
    "quickAnswer": "A container home in Houston starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all-in pricing covering fabrication, delivery, and installation, with the delivery distance from our Oklahoma City, Oklahoma facility factored into every regional quote.",
    "note": "Because units ship from Oklahoma, the Houston delivery leg is longer than for our local builds, and that distance is reflected transparently in your quote rather than hidden in fees.",
    "faqs": [
      {
        "q": "Is delivery to Houston included in the price?",
        "a": "Yes. Our starting prices are all-in — fabrication, delivery, and installation. The longer haul from Oklahoma City, Oklahoma to the Houston area is accounted for upfront, not tacked on later."
      },
      {
        "q": "What does a modular pool cost in Houston?",
        "a": "Our Tube Steel + Fiberglass pools start at $48,000, and Welded Steel + Epoxy pools start at $52,000, depending on size and configuration."
      }
    ]
  },
  {
    "slug": "san-antonio",
    "city": "San Antonio",
    "stateAbbr": "TX",
    "quickAnswer": "In San Antonio, a SaltGrass container home starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — each figure all-in for fabrication, delivery, and installation, with the trip from our Oklahoma City, Oklahoma facility already included.",
    "note": "San Antonio is a regional delivery for us, so the haul from Oklahoma is longer than a local job and we quote that distance honestly up front.",
    "faqs": [
      {
        "q": "Are there extra delivery charges to San Antonio?",
        "a": "No surprise add-ons. The starting prices are all-in and already account for the distance from Oklahoma City, Oklahoma to the San Antonio area."
      },
      {
        "q": "How long until my San Antonio home is move-in ready?",
        "a": "Plan on roughly 8 to 9 months from design to install. Factory fabrication overlaps with your local site prep and permitting, which keeps the overall schedule tight."
      }
    ]
  },
  {
    "slug": "austin",
    "city": "Austin",
    "stateAbbr": "TX",
    "quickAnswer": "A container home in Austin starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all-in prices covering fabrication, delivery, and installation, with the haul from our Oklahoma City, Oklahoma shop reflected in the quote.",
    "note": "Since we build in Oklahoma and deliver to Central Texas, Austin's transport leg is a longer one, and we state that distance plainly rather than burying it.",
    "faqs": [
      {
        "q": "Does the Austin price include installation?",
        "a": "Yes. Every starting price is all-in: fabrication at our Oklahoma facility, delivery to your Austin-area site, and installation are all covered."
      },
      {
        "q": "What do modular pools cost near Austin?",
        "a": "Tube Steel + Fiberglass pools start at $48,000, while Welded Steel + Epoxy pools start at $52,000, based on size and finish."
      }
    ]
  },
  {
    "slug": "fort-worth",
    "city": "Fort Worth",
    "stateAbbr": "TX",
    "quickAnswer": "In Fort Worth, a SaltGrass container home starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all figures all-in across fabrication, delivery, and installation, with delivery from Oklahoma City, Oklahoma included.",
    "note": "Fort Worth is one of our closer Texas routes from Oklahoma, but it's still a regional delivery, and that distance is reflected openly in your quote.",
    "faqs": [
      {
        "q": "Are delivery and setup part of the Fort Worth price?",
        "a": "Yes. The starting prices are all-in and cover delivery from our Oklahoma facility plus on-site installation — no separate transport invoice."
      },
      {
        "q": "What's the timeline for a Fort Worth project?",
        "a": "About 8 to 9 months from design to install. Your unit is fabricated at the same time your site is being prepped and permits are processed, which keeps the schedule efficient."
      }
    ]
  },
  {
    "slug": "wichita",
    "city": "Wichita",
    "stateAbbr": "KS",
    "quickAnswer": "A container home in Wichita starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all-in pricing for fabrication, delivery, and installation, with the relatively short trip from our Oklahoma City, Oklahoma facility built in.",
    "note": "Wichita is one of our nearer regional routes from Oklahoma, and even so the delivery distance is stated clearly in every quote.",
    "faqs": [
      {
        "q": "Is delivery to Wichita figured into the price?",
        "a": "Yes. Starting prices are all-in. Because Wichita is closer to our Oklahoma shop than many of our routes, the delivery leg is shorter, and it's already part of the quoted number."
      },
      {
        "q": "How much is a modular pool near Wichita?",
        "a": "Tube Steel + Fiberglass pools start at $48,000, and Welded Steel + Epoxy pools start at $52,000, depending on the size and build you choose."
      }
    ]
  },
  {
    "slug": "kansas-city",
    "city": "Kansas City",
    "stateAbbr": "MO",
    "quickAnswer": "In Kansas City, a SaltGrass container home starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all-in prices for fabrication, delivery, and installation, with the haul from our Oklahoma City, Oklahoma facility included.",
    "note": "Kansas City is a regional delivery from our Oklahoma shop, and that travel distance is shown plainly in your quote rather than hidden as an extra.",
    "faqs": [
      {
        "q": "Does the Kansas City price cover delivery?",
        "a": "Yes. The starting prices are all-in — fabrication, delivery from Oklahoma, and installation are all included in the quoted figure."
      },
      {
        "q": "What's the build timeline for a Kansas City project?",
        "a": "Roughly 8 to 9 months from design to install. Your unit is being built at the factory while your site is prepped and permits move forward, which keeps the timelines overlapping instead of sequential."
      }
    ]
  },
  {
    "slug": "st-louis",
    "city": "St. Louis",
    "stateAbbr": "MO",
    "quickAnswer": "A container home in St. Louis start at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all-in pricing covering fabrication, delivery, and installation, with the distance from our Oklahoma City, Oklahoma facility factored in.",
    "note": "St. Louis is a regional delivery from Oklahoma, so the haul is longer than a local job, and we quote that distance honestly instead of folding it into vague fees.",
    "faqs": [
      {
        "q": "Is delivery to St. Louis included?",
        "a": "Yes. All starting prices are all-in and already account for delivery from Oklahoma City, Oklahoma to the St. Louis area, plus on-site installation."
      },
      {
        "q": "How much does a modular pool cost near St. Louis?",
        "a": "Tube Steel + Fiberglass pools start at $48,000, and Welded Steel + Epoxy pools start at $52,000, depending on size and configuration."
      }
    ]
  },
  {
    "slug": "little-rock",
    "city": "Little Rock",
    "stateAbbr": "AR",
    "quickAnswer": "In Little Rock, a SaltGrass container home starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — every price all-in for fabrication, delivery, and installation, with the short trip from our Oklahoma City, Oklahoma shop included.",
    "note": "Little Rock is one of our nearer regional routes from Oklahoma, and the delivery distance is still stated openly in each quote.",
    "faqs": [
      {
        "q": "Are delivery and installation part of the Little Rock price?",
        "a": "Yes. The starting prices are all-in. Since Little Rock is relatively close to our Oklahoma facility, the delivery leg is shorter, and it's already included in the quoted number."
      },
      {
        "q": "How long does a Little Rock build take?",
        "a": "About 8 to 9 months from design to install. Your unit is fabricated while your site is prepped and permits are processed, so the phases run in parallel rather than back-to-back."
      }
    ]
  },
  {
    "slug": "albuquerque",
    "city": "Albuquerque",
    "stateAbbr": "NM",
    "quickAnswer": "A container home in Albuquerque starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all-in pricing for fabrication, delivery, and installation, with the longer haul from our Oklahoma City, Oklahoma facility factored into the quote.",
    "note": "Albuquerque is one of our farther regional routes from Oklahoma, so the transport leg is longer than most, and we reflect that distance honestly in your quote.",
    "faqs": [
      {
        "q": "Does the Albuquerque price include the longer delivery?",
        "a": "Yes. All starting prices are all-in and already account for the longer trip from Oklahoma City, Oklahoma to the Albuquerque area, plus on-site installation."
      },
      {
        "q": "What do modular pools cost in Albuquerque?",
        "a": "Tube Steel + Fiberglass pools start at $48,000, and Welded Steel + Epoxy pools start at $52,000, depending on size and finish."
      }
    ]
  },
  {
    "slug": "new-orleans",
    "city": "New Orleans",
    "stateAbbr": "LA",
    "quickAnswer": "A SaltGrass container home in New Orleans starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in (fabrication, delivery, and installation), with delivery hauled from our Oklahoma City, Oklahoma facility within regional reach of Louisiana.",
    "note": "Because New Orleans is within our regional delivery zone, transport from Oklahoma is a manageable part of the all-in figure rather than a long-distance surcharge.",
    "faqs": [
      {
        "q": "Is delivery to New Orleans included in the price?",
        "a": "Yes. Our published starting prices are all-in and already account for fabrication, delivery, and installation. New Orleans sits within regional reach of our Oklahoma shop, so that haul is built into the quote."
      },
      {
        "q": "What does a modular pool cost in the New Orleans area?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, and a Welded Steel and Epoxy pool start at $52,000. Final pricing depends on size and site conditions."
      }
    ]
  },
  {
    "slug": "omaha",
    "city": "Omaha",
    "stateAbbr": "NE",
    "quickAnswer": "A SaltGrass container home in Omaha starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in covering fabrication, delivery, and installation, with the unit hauled from our Oklahoma City, Oklahoma facility within regional reach of Nebraska.",
    "note": "Omaha falls inside our regional delivery zone, so the trip from Oklahoma is folded into the all-in price rather than charged as a long-haul extra.",
    "faqs": [
      {
        "q": "Are the Omaha prices truly all-in?",
        "a": "Yes. The starting figures bundle fabrication, delivery, and installation. Since Omaha is within regional reach of our Oklahoma facility, the transport leg is already part of the number you see."
      },
      {
        "q": "What affects the final cost beyond the starting price?",
        "a": "Layout, finishes, site conditions, and any pool or add-ons move the total. A modular pool, for example, start at $48,000 for Tube Steel and Fiberglass or at $52,000 for Welded Steel and Epoxy."
      }
    ]
  },
  {
    "slug": "denver",
    "city": "Denver",
    "stateAbbr": "CO",
    "quickAnswer": "A SaltGrass container home in Denver starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in including fabrication, delivery, and installation, with delivery driven from our Oklahoma City, Oklahoma facility within regional reach of Colorado.",
    "note": "Denver is inside our regional delivery zone, so the run from Oklahoma is part of the all-in cost instead of a separate long-distance fee.",
    "faqs": [
      {
        "q": "Does the Denver price include getting the home up the mountains?",
        "a": "The starting prices are all-in for fabrication, delivery, and installation, and Denver sits within our regional reach. We confirm site access during planning so the delivery leg is locked in before you commit."
      },
      {
        "q": "What would a modular pool add in the Denver area?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, while a Welded Steel and Epoxy pool start at $52,000, with the final figure shaped by size and site prep."
      }
    ]
  },
  {
    "slug": "colorado-springs",
    "city": "Colorado Springs",
    "stateAbbr": "CO",
    "quickAnswer": "A SaltGrass container home in Colorado Springs starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in for fabrication, delivery, and installation, with the unit transported from our Oklahoma City, Oklahoma facility within regional reach of Colorado.",
    "note": "Since Colorado Springs is within our regional delivery zone, the trip from Oklahoma is part of the all-in number rather than a long-haul surcharge.",
    "faqs": [
      {
        "q": "Is the Colorado Springs quote all-inclusive?",
        "a": "Yes. The starting prices roll fabrication, delivery, and installation into one figure, and Colorado Springs is within regional reach of our Oklahoma shop, so the delivery leg is baked in."
      },
      {
        "q": "How much does a modular pool cost in Colorado Springs?",
        "a": "Expect at $48,000 for a Tube Steel and Fiberglass pool and at $52,000 for a Welded Steel and Epoxy pool, with final pricing depending on size and your site."
      }
    ]
  },
  {
    "slug": "phoenix",
    "city": "Phoenix",
    "stateAbbr": "AZ",
    "quickAnswer": "A SaltGrass container home in Phoenix starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in covering fabrication, delivery, and installation, with the unit shipped nationally from our Oklahoma City, Oklahoma facility, a longer haul than our regional markets.",
    "note": "Because Phoenix sits well beyond our regional zone, the longer delivery distance from Oklahoma is reflected honestly in project planning, though it remains part of the all-in figure.",
    "faqs": [
      {
        "q": "Does the Phoenix price account for the long delivery from Oklahoma?",
        "a": "Yes. Our starting prices are all-in for fabrication, delivery, and installation. We're a national builder, and we plan the longer haul to Arizona into the quote so there are no delivery surprises."
      },
      {
        "q": "What does a modular pool run in the Phoenix area?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, and a Welded Steel and Epoxy pool start at $52,000. Size and site conditions set the final price."
      }
    ]
  },
  {
    "slug": "las-vegas",
    "city": "Las Vegas",
    "stateAbbr": "NV",
    "quickAnswer": "A SaltGrass container home in Las Vegas starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in including fabrication, delivery, and installation, delivered nationally from our Oklahoma City, Oklahoma facility, a longer haul than our regional markets.",
    "note": "Las Vegas lies beyond our regional reach, so the extended delivery distance from Oklahoma is planned into the project honestly while staying inside the all-in price.",
    "faqs": [
      {
        "q": "Is delivery to Las Vegas included even though it's far from Oklahoma?",
        "a": "Yes. The starting prices are all-in for fabrication, delivery, and installation. As a national builder, we account for the longer haul to Nevada when we put the quote together."
      },
      {
        "q": "What would adding a modular pool cost in Las Vegas?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, and a Welded Steel and Epoxy pool start at $52,000, with final pricing set by size and site prep."
      }
    ]
  },
  {
    "slug": "atlanta",
    "city": "Atlanta",
    "stateAbbr": "GA",
    "quickAnswer": "A SaltGrass container home in Atlanta starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in for fabrication, delivery, and installation, shipped nationally from our Oklahoma City, Oklahoma facility, a longer haul than our regional markets.",
    "note": "Since Atlanta is outside our regional zone, the longer delivery distance from Oklahoma is reflected honestly in planning while remaining part of the all-in figure.",
    "faqs": [
      {
        "q": "Are the Atlanta prices all-in despite the distance?",
        "a": "Yes. Fabrication, delivery, and installation are all bundled into the starting prices. We're a national builder and plan the longer haul to Georgia into the quote, so the delivery cost isn't a separate add-on."
      },
      {
        "q": "What does a modular pool cost in the Atlanta area?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, and a Welded Steel and Epoxy pool start at $52,000, with the final number depending on size and site conditions."
      }
    ]
  },
  {
    "slug": "tampa",
    "city": "Tampa",
    "stateAbbr": "FL",
    "quickAnswer": "A SaltGrass container home in Tampa starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in covering fabrication, delivery, and installation, delivered nationally from our Oklahoma City, Oklahoma facility, a longer haul than our regional markets.",
    "note": "Tampa sits well beyond our regional reach, so the longer delivery distance from Oklahoma is accounted for honestly in planning while staying inside the all-in price.",
    "faqs": [
      {
        "q": "Does the Tampa price include the long haul from Oklahoma?",
        "a": "Yes. Our starting prices are all-in for fabrication, delivery, and installation. As a national builder, we plan the longer trip to Florida into the quote so the delivery leg isn't a surprise line item."
      },
      {
        "q": "How much would a modular pool add in Tampa?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, and a Welded Steel and Epoxy pool start at $52,000, with the final figure shaped by size and site prep."
      }
    ]
  },
  {
    "slug": "orlando",
    "city": "Orlando",
    "stateAbbr": "FL",
    "quickAnswer": "A SaltGrass container home in Orlando starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in including fabrication, delivery, and installation, shipped nationally from our Oklahoma City, Oklahoma facility, a longer haul than our regional markets.",
    "note": "Because Orlando is outside our regional zone, the extended delivery distance from Oklahoma is reflected honestly during planning while remaining part of the all-in figure.",
    "faqs": [
      {
        "q": "Are the Orlando prices truly all-in?",
        "a": "Yes. The starting figures bundle fabrication, delivery, and installation into one number. As a national builder, we plan the longer haul to Florida into the quote rather than tacking it on later."
      },
      {
        "q": "What does a modular pool cost in the Orlando area?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, and a Welded Steel and Epoxy pool start at $52,000, with final pricing depending on size and site conditions."
      }
    ]
  },
  {
    "slug": "nashville",
    "city": "Nashville",
    "stateAbbr": "TN",
    "quickAnswer": "A container home in Nashville starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in (fabrication, delivery, and installation) — with delivery running east from our Oklahoma City, Oklahoma facility.",
    "note": "Because every unit ships from Oklahoma, the Nashville delivery leg adds distance, and we quote that leg honestly inside your all-in price.",
    "faqs": [
      {
        "q": "Is delivery to Nashville included in the starting price?",
        "a": "Yes. Our published starting prices are all-in, covering fabrication, the delivery run from Oklahoma City, Oklahoma, and installation. Nashville sits east of our facility, so that distance is factored into the quote rather than billed as a surprise add-on."
      },
      {
        "q": "What does a modular pool cost in the Nashville area?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, and a Welded Steel and Epoxy pool start at $52,000. Final pricing depends on size and configuration."
      }
    ]
  },
  {
    "slug": "charlotte",
    "city": "Charlotte",
    "stateAbbr": "NC",
    "quickAnswer": "In Charlotte, a container home starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all-in pricing covering fabrication, delivery, and installation, with the haul running east from Oklahoma City, Oklahoma.",
    "note": "Charlotte is a longer eastbound delivery from our Oklahoma facility, and we fold that distance transparently into the all-in number rather than tacking it on later.",
    "faqs": [
      {
        "q": "Are there hidden fees on top of the Charlotte starting price?",
        "a": "No. The starting prices are all-in by design — fabrication, the Oklahoma-to-Charlotte delivery leg, and installation are accounted for in the quote. We'd rather show the real number than pad it with surprises."
      },
      {
        "q": "Can I add a modular pool to my Charlotte build?",
        "a": "Yes. Tube Steel and Fiberglass pools start at $48,000, while Welded Steel and Epoxy pools start at $52,000, depending on size and finish."
      }
    ]
  },
  {
    "slug": "phoenix-mesa",
    "city": "Mesa",
    "stateAbbr": "AZ",
    "quickAnswer": "A container home in Mesa starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in (fabrication, delivery, installation) — with delivery hauling west from our Oklahoma City, Oklahoma facility.",
    "note": "Mesa is a westbound delivery from Oklahoma, and that distance is built honestly into the all-in price instead of appearing as a separate charge.",
    "faqs": [
      {
        "q": "Does the Mesa price include the trip from Oklahoma?",
        "a": "It does. Every starting price is all-in, so fabrication, the delivery run from Oklahoma City, Oklahoma to the Phoenix-Mesa area, and installation are already included. The longer western haul is reflected up front in the quote."
      },
      {
        "q": "What does a modular pool add to a Mesa project?",
        "a": "A Tube Steel and Fiberglass pool starts at $48,000, and a Welded Steel and Epoxy pool start at $52,000. The right fit depends on the size and build you want."
      }
    ]
  },
  {
    "slug": "salt-lake-city",
    "city": "Salt Lake City",
    "stateAbbr": "UT",
    "quickAnswer": "In Salt Lake City, a container home starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all-in covering fabrication, delivery, and installation, with the haul running northwest from Oklahoma City, Oklahoma.",
    "note": "Salt Lake City is a longer northwestern delivery from our Oklahoma shop, and we account for that distance openly within the all-in price.",
    "faqs": [
      {
        "q": "Is the delivery distance to Salt Lake City an extra charge?",
        "a": "No. Our starting prices are all-in, so the delivery leg from Oklahoma City, Oklahoma to the Salt Lake metro is already part of the quote alongside fabrication and installation. We price the real distance rather than adding it after the fact."
      },
      {
        "q": "How much is a modular pool in the Salt Lake area?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, and a Welded Steel and Epoxy pool start at $52,000, with final cost set by size and configuration."
      }
    ]
  },
  {
    "slug": "boise",
    "city": "Boise",
    "stateAbbr": "ID",
    "quickAnswer": "A container home in Boise starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in (fabrication, delivery, and installation) — with delivery running northwest from our Oklahoma City, Oklahoma facility.",
    "note": "Boise is one of the longer northwestern delivery legs from Oklahoma, and we reflect that distance honestly inside the all-in price.",
    "faqs": [
      {
        "q": "Does the Boise starting price cover shipping from Oklahoma?",
        "a": "Yes. The starting prices are all-in, so fabrication, the long delivery run from Oklahoma City, Oklahoma to the Boise area, and installation are all included. We quote the actual distance rather than hiding it in fees."
      },
      {
        "q": "What's the cost of adding a modular pool in Boise?",
        "a": "Tube Steel and Fiberglass pools start at $48,000, and Welded Steel and Epoxy pools start at $52,000. The final figure depends on the size and build you choose."
      }
    ]
  },
  {
    "slug": "oklahoma-city-norman",
    "city": "Norman",
    "stateAbbr": "OK",
    "quickAnswer": "In the Norman and Oklahoma City area, a container home starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom — all-in for fabrication, delivery, and installation, with one of the shortest delivery legs from our Oklahoma City, Oklahoma facility.",
    "note": "Because Norman is in our home state, the delivery distance from Oklahoma City is short, and that's reflected in a straightforward all-in price.",
    "faqs": [
      {
        "q": "Is delivery cheaper because Norman is in Oklahoma?",
        "a": "The starting prices are all-in regardless of location, and Norman benefits from being close to our Oklahoma City facility — one of the shortest delivery legs we run. Fabrication, delivery, and installation are all included in the quote."
      },
      {
        "q": "What does a modular pool cost near Norman?",
        "a": "A Tube Steel and Fiberglass pool start at $48,000, and a Welded Steel and Epoxy pool start at $52,000, depending on the size and configuration you select."
      }
    ]
  },
  {
    "slug": "broken-arrow",
    "city": "Broken Arrow",
    "stateAbbr": "OK",
    "quickAnswer": "A container home in Broken Arrow starts at $75,000 for a 320 SF studio, $105,000 for a 640 SF one-bedroom, and $155,000 for a 960 SF two-bedroom, all-in (fabrication, delivery, and installation) — with one of the shortest delivery distances from our nearby Oklahoma City, Oklahoma facility.",
    "note": "Broken Arrow's short distance from Oklahoma City keeps the delivery leg minimal, and that's reflected plainly in the all-in price.",
    "faqs": [
      {
        "q": "Does being near Oklahoma City lower the Broken Arrow cost?",
        "a": "Our starting prices are all-in for every location, and Broken Arrow's proximity to Oklahoma City means one of our shortest delivery runs. Fabrication, delivery, and installation are all rolled into the quoted price."
      },
      {
        "q": "How much is a modular pool in Broken Arrow?",
        "a": "A Tube Steel and Fiberglass pool starts at $48,000, and a Welded Steel and Epoxy pool start at $52,000. Final pricing depends on the size and finish you go with."
      }
    ]
  }
];
