import type { GlossaryTerm } from './types';

// AUTO-GENERATED by the content workflow (do not hand-edit — regenerate instead).
export const GENERATED_GLOSSARY: GlossaryTerm[] = [
  {
    "slug": "module",
    "term": "Module",
    "short": "A factory-built three-dimensional building section shipped whole and joined on site.",
    "long": "A module is a complete volumetric box-like section of a building assembled in a factory, including floors, walls, ceiling, and often finishes, wiring, and plumbing. Multiple modules are transported to the site and connected to form the finished structure. Module count and dimensions are usually limited by road-transport width and height restrictions."
  },
  {
    "slug": "chassis",
    "term": "Chassis",
    "short": "The steel frame and wheels that support a transportable building during travel.",
    "long": "A chassis is the structural steel base, typically with axles, wheels, and a hitch, that carries a manufactured unit over the road. In manufactured (HUD) homes the chassis stays permanently as part of the structure, while in modular construction a temporary carrier or flatbed is used and removed after placement. The distinction affects code classification, financing, and foundation requirements."
  },
  {
    "slug": "on-frame-vs-off-frame",
    "term": "On-Frame vs. Off-Frame",
    "short": "Whether a transportable unit keeps its steel carrier frame or is lifted off it onto a foundation.",
    "long": "On-frame construction leaves the unit permanently attached to its steel transport frame, common in manufactured homes and some modular units placed on piers. Off-frame (or off-chassis) construction lifts the building off the carrier and sets it directly on a permanent foundation, allowing it to be treated more like site-built construction. The choice influences appraisal, code path, and the type of foundation required."
  },
  {
    "slug": "set-crew",
    "term": "Set Crew",
    "short": "The specialized team that cranes modules onto the foundation and mates them together.",
    "long": "A set crew handles the on-site placement of factory-built modules, operating or directing the crane, aligning units on the foundation, and bolting or welding them together. They typically work for a day or two during the 'set,' which is the most weather- and logistics-sensitive part of a modular build. Their work precedes the button-up and finishing trades."
  },
  {
    "slug": "button-up",
    "term": "Button-Up",
    "short": "The on-site finishing work that closes the seams where modules meet.",
    "long": "Button-up refers to all the tasks needed to make separately delivered modules into one weather-tight, continuous building after they are set. This includes sealing roof and wall mate-lines, connecting electrical and plumbing across modules, patching drywall seams, and completing flooring and trim at the joints. Button-up scope and quality vary by manufacturer and directly affect how 'seamless' the finished home looks."
  },
  {
    "slug": "r-value-insulation",
    "term": "R-Value / Insulation",
    "short": "A measure of how well insulation resists heat flow; higher R-value means better insulation.",
    "long": "R-value quantifies a material's thermal resistance, with higher numbers indicating greater resistance to heat transfer through walls, roofs, and floors. Building codes set minimum R-values by climate zone, and modular and container structures must meet these just like site-built homes. Because container and tiny-home walls are thin, achieving required R-values often relies on spray foam or rigid-board insulation rather than standard batts."
  },
  {
    "slug": "irc-ibc-code",
    "term": "IRC / IBC Code",
    "short": "The model building codes governing residential (IRC) and commercial/multi-family (IBC) construction.",
    "long": "The International Residential Code (IRC) covers one- and two-family dwellings, while the International Building Code (IBC) covers commercial buildings and most multi-family and larger structures. Jurisdictions adopt and amend specific editions of these codes, which set requirements for structure, egress, fire safety, and energy use. Modular buildings are typically built to the same IRC or IBC edition the local jurisdiction enforces, verified through a state modular program or third-party inspection."
  },
  {
    "slug": "snow-load",
    "term": "Snow Load",
    "short": "The downward weight a roof must safely carry from accumulated snow.",
    "long": "Snow load is the design weight, expressed in pounds per square foot, that a roof structure must support based on local climate data. Higher-snow regions require stronger roof framing, steeper pitches, or upgraded structural design. Buyers placing a modular or container building should confirm the unit's rated ground snow load matches their site's requirement set by the local authority."
  },
  {
    "slug": "seismic-design",
    "term": "Seismic Design",
    "short": "Engineering that lets a structure resist earthquake forces without collapsing.",
    "long": "Seismic design addresses the lateral and dynamic forces an earthquake imposes on a building, governed by seismic design categories tied to a site's ground-shaking risk. It dictates anchoring, bracing, connection strength, and foundation detailing, and is especially important for how modules attach to each other and to the foundation. In higher-risk zones, modular and container structures need engineered tie-downs and reinforced connections to comply."
  },
  {
    "slug": "shipping-container-iso-high-cube",
    "term": "Shipping Container (ISO / High-Cube)",
    "short": "A standardized steel freight box; high-cube adds about a foot of interior height.",
    "long": "Shipping containers are corrugated steel boxes built to ISO standards for global freight, most commonly 20 or 40 feet long and about 8 feet wide. A standard container is roughly 8 feet 6 inches tall, while a high-cube container is about 9 feet 6 inches, giving extra headroom that matters once floor and ceiling insulation reduce interior height. Container builders favor high-cube units and prefer one-trip or new containers to avoid contamination and rust found in heavily used boxes."
  },
  {
    "slug": "corten-steel",
    "term": "Corten Steel",
    "short": "A weathering steel that forms a stable rust-like surface, used in shipping containers.",
    "long": "Corten, or weathering steel, is an alloy that develops a protective oxide layer when exposed to the elements, slowing further corrosion without paint. Shipping containers are commonly made from Corten-type steel, which gives them durability but does not make them rust-proof, especially at cut edges and welds. Buyers modifying containers must protect newly exposed steel from moisture to prevent ongoing corrosion."
  },
  {
    "slug": "foundation-types",
    "term": "Foundation Types (Pier / Slab / Crawlspace)",
    "short": "The main ways a structure is supported on the ground: piers, a concrete slab, or a raised crawlspace.",
    "long": "A pier foundation uses isolated columns or piles to lift the structure off the ground, common for containers and modular units on sloped or remote sites. A slab is a continuous poured-concrete floor that sits at grade, while a crawlspace raises the building on perimeter walls with an accessible gap underneath for utilities. The right choice depends on soil conditions, frost depth, flood risk, and how the building will be anchored against wind and seismic loads."
  },
  {
    "slug": "egress",
    "term": "Egress",
    "short": "A code-required exit path, including windows large enough to escape through.",
    "long": "Egress refers to the means of safely exiting a building in an emergency, and codes require habitable rooms—especially bedrooms—to have a properly sized exit. An egress window must meet minimum opening dimensions and sill height so an occupant can escape and a firefighter can enter. Container and tiny-home conversions frequently need steel cut and reframed to add compliant egress openings."
  },
  {
    "slug": "gray-water",
    "term": "Gray Water",
    "short": "Lightly used wastewater from sinks, showers, and laundry, separate from toilet waste.",
    "long": "Gray water is the relatively clean wastewater from showers, bathroom sinks, and washing machines, as opposed to black water from toilets. Where local code allows, it can be captured and reused for irrigation or filtered for non-potable uses, reducing freshwater demand in off-grid or sustainable builds. Gray-water systems are regulated separately from sewage and require approval from the local health or plumbing authority."
  },
  {
    "slug": "net-zero",
    "term": "Net-Zero",
    "short": "A building that produces as much energy over a year as it consumes.",
    "long": "A net-zero building balances its total annual energy use with on-site renewable generation, typically solar, so its net energy purchase is around zero. Reaching net-zero relies on a tight, well-insulated envelope, efficient mechanical systems, and adequate renewable capacity. Compact modular and container homes can pursue net-zero relatively easily because their smaller conditioned volume lowers total energy demand."
  },
  {
    "slug": "hvac-mini-split",
    "term": "HVAC Mini-Split",
    "short": "A ductless heat-pump system with an outdoor unit and one or more wall-mounted indoor heads.",
    "long": "A mini-split is a ductless heating and cooling system that pairs an outdoor compressor with indoor air-handling heads connected by refrigerant lines. It is popular in modular, container, and tiny-home builds because it needs no ductwork, fits compact spaces, and offers efficient zoned temperature control. Multiple indoor heads can run from one outdoor unit, allowing room-by-room comfort in small footprints."
  },
  {
    "slug": "factory-qc",
    "term": "Factory QC",
    "short": "Controlled in-plant quality inspection of modular units before they ship.",
    "long": "Factory quality control is the structured inspection and testing process applied to modules as they are built indoors, often by in-house inspectors plus an independent third-party agency. Because work happens in a controlled environment with repeatable processes, defects can be caught and corrected before the unit leaves the plant. This documented QC is a key reason modular construction can offer more consistent build quality than fully site-built work."
  },
  {
    "slug": "panelized",
    "term": "Panelized",
    "short": "Construction using flat factory-built wall, floor, and roof panels assembled on site.",
    "long": "Panelized construction prefabricates two-dimensional components—wall, floor, and roof panels—in a factory and ships them flat to be erected and connected on site. Unlike volumetric modular building, panels arrive open rather than as finished rooms, which lowers shipping cost but shifts more assembly and finishing work to the job site. It is a middle ground between full modular and traditional stick-building."
  },
  {
    "slug": "manufactured-hud-home",
    "term": "Manufactured (HUD) Home",
    "short": "A factory-built home built to the federal HUD code on a permanent steel chassis.",
    "long": "A manufactured home is built entirely in a factory to the federal HUD Code rather than to local IRC/IBC codes, and it retains a permanent steel chassis. This federal standard, financing treatment, and chassis distinguish it from modular homes, which are built to the same local codes as site-built houses. The classification affects where the home can be placed, how it is financed, and how it appraises."
  },
  {
    "slug": "modular-tiny-home",
    "term": "Modular Tiny Home",
    "short": "A very small factory-built dwelling, typically under about 400 square feet.",
    "long": "A modular tiny home is a compact factory-built dwelling, generally below roughly 400 square feet, designed as a permanent or semi-permanent residence. Built to applicable residential codes, it differs from tiny homes on wheels, which are often regulated as recreational vehicles. Tiny homes frequently serve as accessory dwellings, guest spaces, or affordable standalone housing on a permanent foundation."
  },
  {
    "slug": "fabrication",
    "term": "Fabrication",
    "short": "The factory or shop process of building and assembling structural components.",
    "long": "Fabrication is the manufacturing phase where raw materials—steel, lumber, panels—are cut, welded, framed, and assembled into modules or building components. In container and modular work it covers structural modifications such as cutting openings, reinforcing the frame, and installing systems before delivery. Quality of fabrication directly determines structural integrity, weather-tightness, and ease of on-site assembly."
  },
  {
    "slug": "draw-schedule",
    "term": "Draw Schedule",
    "short": "A payment plan releasing funds in stages as construction milestones are completed.",
    "long": "A draw schedule is the agreed sequence of partial payments, or draws, released to the builder as defined milestones are reached, such as deposit, factory completion, delivery, and final finish. It protects both buyer and lender by tying money to verifiable progress rather than paying everything upfront. Modular projects often front-load draws because much of the value is built in the factory before site work begins, which buyers should review carefully."
  },
  {
    "slug": "certificate-of-occupancy",
    "term": "Certificate of Occupancy",
    "short": "The official document confirming a building is code-compliant and legal to occupy.",
    "long": "A certificate of occupancy (CO) is issued by the local building department after final inspections confirm a structure meets applicable codes and is safe to live in or use. For modular and container projects, the CO depends on completed foundation, utility hookups, button-up, and site work passing inspection, not just factory completion. Without a CO, a building generally cannot be legally occupied, insured, or sometimes financed."
  }
];
